export const GET_ALL_COCKTAILS = 'GET_ALL_COCKTAILS';

export const CREATE_NEW_ACCOUNT = 'CREATE_NEW_ACCOUT';
export const REGULAR_SIGN_IN = 'REGULAR_SIGN_IN';
export const OAUTH_SIGN_IN = 'OAUTH_SIGN_IN';
